 export const DISPLAY_PRODUCTS = 'DISPLAY_PRODUCTS';
 export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';
 export const DISPLAY_PRODUCTS_SUCCESS = 'DISPLAY_PRODUCTS_SUCCESS';
 export const ADD_PRODUCT = 'ADD_PRODUCT';


 //display product by id
 export const DISPLAY_PRODUCT = 'DISPLAY_PRODUCT';
 export const DISPLAY_PRODUCT_FAILED = 'DISPLAY_PRODUCT_FAILED';
 export const DISPLAY_PRODUCT_SUCCESS = 'DISPLAY_PRODUCT_SUCCESS';

//customer profile
export const GET_CUSTOMER = 'GET_CUSTOMERS';
export const CUSTOMERS_FAILED = 'GET_CUSTOMERS';
export const CUSTOMERS_LOADING = 'GET_CUSTOMERS';


//cart
export const GET_CART = 'GET_CART';
export const ADD_SHOE_TO_CART = 'ADD_TO_CART';
export const REMOVE_SHOE_FROM_CART = 'REMOVE_SHOE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const CART_FAILED = 'GET_CART';
export const CART_LOADING = 'CART_LOADING';

//orders
export const GET_ORDERS = 'GET_ORDERS';
export const ADD_ORDERS = 'ADD_ORDERS';
export const DELETE_ORDER = 'DELETE_ORDER';
export const ORDERS_FAILED = 'ORDERS_FAILED';
export const ORDERS_LOADING = 'ORDERS_LOADING';


//Shipping Info
export const EDIT_SHIPPING_INFO = 'EDIT_SHIPPING_INFO';
export const SHIPPING_INFO_LOADING = 'SHIPPING_INFO_LOADING';
export const SHIPPING_INFO_FAILED = 'SHIPPING_INFO_FAILED';


